{% set version = "2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ascii
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ascii_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ascii/ascii_{{ version }}.tar.gz
  sha256: 13459e7a6ab25014c72dc3e435c1b8685b85622aaf51cee430aeecab1918e3f2

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-codetools
    - r-digest
    - r-survival
  run:
    - r-base
    - r-codetools
    - r-digest
    - r-survival

test:
  commands:
    - $R -e "library('ascii')"           # [not win]
    - "\"%R%\" -e \"library('ascii')\""  # [win]

about:
  home: http://eusebe.github.com/ascii/, http://github.com/eusebe/ascii/
  license: GPL-2.0-or-later
  summary: Coerce R object to asciidoc, txt2tags, restructuredText, org, textile or pandoc syntax.  Package comes with a set of drivers for Sweave.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - Adrianzo

# Package: ascii
# Maintainer: David Hajage <dhajage@gmail.com>
# License: GPL (>= 2)
# Title: Export R objects to several markup languages
# Type: Package
# Author: David Hajage
# Description: Coerce R object to asciidoc, txt2tags, restructuredText, org, textile or pandoc syntax.  Package comes with a set of drivers for Sweave.
# Version: 2.1
# URL: http://eusebe.github.com/ascii/, http://github.com/eusebe/ascii/
# Date: 2009-07-20
# Depends: R (>= 2.13), utils, methods
# Suggests: survival, Hmisc, xtable, R2HTML, cacheSweave, weaver
# Collate: 'asciiAnova.r' 'asciiDataFrame.r' 'asciiDefault.r' 'asciiDensity.r' 'asciiDescr.r' 'asciiEpi.r' 'asciiGlm.r' 'asciiHmisc.r' 'asciiHtest.r' 'asciiList.r' 'asciiLm.r' 'asciiMatrix.r' 'asciiMemisc.r' 'asciiPrcomp.r' 'asciiSmoothSpline.r' 'asciiSummaryTable.r' 'asciiSurvival.r' 'asciiTable.r' 'asciiTs.r' 'asciiVector.r' 'cacheSweaveAscii.r' 'cbind.r' 'export.r' 'generic.r' 'groups.r' 'interleave.r' 'paste.matrix.r' 'plim.r' 'print.character.matrix.r' 'RweaveAscii.r' 'show.asciidoc.r' 'show.org.r' 'show.pandoc.r' 'show.r' 'show.rest.r' 'show.t2t.r' 'show.textile.r' 'SweaveAscii.r' 'tocharac.r' 'weaverAscii.r' 'zzz.r' 'print.r'
# Packaged: 2011-09-28 08:59:12 UTC; david
# Repository: CRAN
# Date/Publication: 2011-09-29 11:27:34
