travis:
  secure:
    BINSTAR_TOKEN: O7SmnXgfnxZ14BC7E3HALYglRNaO3+kGUAQiQdywu13CT2eWlN244bp24mZuVSRPF3LbmMHiWxZ/qQKgWQdhkcO9OLa7M72eyw1CGHcXUsDOGikoaHR3jVVqH1NYhUJI4BQ5DLp5ftsmiowwp4m0aji7jzTEs40RsUblXRhImHIYrVI+CZyL9gPKyNd1awM/VX9WGihv/bGbu6i983H8i1+KqCpiKOVVzxUk7sgfgPqe/SZ0qqhjTivHEJH05AvytUmoJHh0XwfYVozyP5Ncvif9JQ9JGGbxIfKgZAM+aK+rc9LRU83SiVxmN7nWYXEMto8FiN9emaXt6ZhEHq6abzhWcPSIYU00snK2x4Uf/zNo4z+W2YaGOtG5sKOwWID0Pdi1JZCgent9snwQOJqqpYQ44YkBgkE9RMAtxlBmBSvfWqyfi88idZx63kCJkbVrR8O8goB6Rqm1p3Qyn1HFUHuc2lW1XbDulal1IrftktOzLiVZt5m/LCjLW9gLPAT8I0t3ay9ikPfe0t/t3lAcWs67UkKNyyFV7SumNEYixeinBTxOLXu+x37tNtIr08seXINQ7pMplizUJOnI2Vpd5xHrpcaLkexLVvL8Eq9NBkSr0HqoXQuLwlBrLLJTTzFuvBdFFCwSsN3A/WwS7WJVoH/nVuhrdfb8nit+X68M6FM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
